version: '3.4'

services:
  authorization.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
    image: authorizationapi
    container_name: AuthorizationAPI
    build:
      context: .
      args:
      - BUILD_CONFIGURATION=Development
      dockerfile: AuthorizationAPI/AuthorizationAPI.Web/Dockerfile
    ports:
    -  "5000:5000"
    # depends_on:
    #     mssql-server:
    #         condition: service_healthy
  
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql-server
    environment:
        ACCEPT_EULA: Y
        SA_PASSWORD: SecretPassword123
    volumes:
        - ./sqlserver/data:/var/opt/mssql/data
        - ./sqlserver/log:/var/opt/mssql/log
    ports: 
        - "1433:1433"
    # healthcheck:
    #     test: /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "SecretPassword123" -Q "Select 1" -b -o /dev/null
    #     interval: 10s
    #     timeout: 3s
    #     retries: 10
    #     start_period: 10s

